export const profileOfOba = [
    {
        id:1,
        image: "https://atuwatseiii.com/assets/img/crests/iwere_kings/atuwatse_iii.jpg",
        name: "Olu Atuwatse III",
        span: "Present",
        reign: 'Reign' ,
        start: '<b>Start:</b> 21 August 2021' ,
        end: '<b>End:</b>' ,
        biography: '21st Olu. Tsola Emiko born to Olu Atuwatse II and Olori Gladys Durorike Emiko on 2 April 1984. He succeeded his uncle and is married to Olori Ivie Emiko (née Okunbo). They have three children.'  
    },
    {
        id:2,
        image: "https://atuwatseiii.com/assets/img/crests/iwere_kings/ikenwoli.jpg",
        name: "Ikenwoli I Godfery Emiko",
        span: "19 March 1955 – 21 December 2020",
        reign: 'Reign' ,
        start: '<b>Start:</b> 12 December 2015' ,
        end: '<b>End:</b> 21 December 2020' ,
        family: "Itsekiri",
        biography: "20th Olu. Ikenwoli Godfrey Emiko born to Olu Erejuwa II and Olori Eyinagboluwade Emiko. He succeeded his elder brother and was married to Olori Mary Emiko. They had three children."
    },
    {
        id:3,
        image:  "https://atuwatseiii.com/assets/img/crests/iwere_kings/atuwatse_ii.jpg",
        name: "Olu Atuwatse II Godwin Toritseju Emiko",
        span: "c.1945 - 5 September 2015",
        reign: 'Reign' ,
        start: "<b>Start:</b> 2 May 1987",
        end: "<b>End:<b> 5 September 2015",
        family: "Itsekiri",
        biography: "19th Olu. He was born Godwin Toritseju Emiko. He succeeded his father. He was a lawyer by profession and was a recipient of the Commander of the Niger (CON) award from the Nigerian Government. Atuwatse II died in a hospital in Lagos in early September 2015, after suffering a domestic accident. He was 70 years old, and was preparing to fly abroad to receive intensive medical care before his condition worsened."
    },
    {
        id:4,
        image: "https://atuwatseiii.com/assets/img/crests/iwere_kings/erejuwa_ii.jpg",
        name: "Erejuwa II Wilson Ayoronmitsi Gbesimi Emiko",
        span: "c.1908 - 17 December 1986)",
        reign: 'Reign' ,
        start: "<b>Start:</b> 24 March 1951",
        end: "<b>End:<b> 17 December 1986",
        family: "Itsekiri",
        biography: "18th Olu. He succeeded his father. He attended a CMS missionary school at Ogbesse, thereafter he did business with United African Company rising to become a provincial cooperatives president. As Olu of Warri, he was appointed regional Minister without portfolio and president of the Warri Divisional Traditional Council."
    },
    {
        id:5,
        image: "https://atuwatseiii.com/assets/img/crests/iwere_kings/ginuwa_ii.jpg",
        name: "Ginuwa II Emiko Ikengbuwa",
        span: "7 February 1936 ",
        reign: 'Reign' ,
        start: "<b>Start:</b> Unknown - 1949",
        end: "<b>End:<b> 8 January 1949",
        family: "Itsekiri",
        biography: "17th Olu. He was a Nigerian traditional title holder and paramount leader of the Itsekiri. He was born Emiko Ikengbuwa. He succeeded his grandfather Olu Akengbuwa as Olu of Warri after an interregnum that lasted 88 years when Warri's political leadership was dominated by merchant princes."
    },
    {
        id:6,
        image: "https://atuwatseiii.com/assets/img/crests/iwere_kings/interregnum.jpg",
        name: "Interregnum",
        span: "14 June 1848 – 7 February 1936 (87 years)",
        reign: 'Reign' ,
        start: "<b>Start:<b>14 June 1848",
        end: "<b>End:<b> 7 February 1936",
        family: "",
        biography: "After the death of Olu Dom Eyeolusan João Akengbuwa there was a dynastic crisis following the death of all the potential successors which was followed by a period of political Interregnum. His son Prince Oritsemone left Ode-Itsekiri during the period of the crisis to form the Usele Community. Queen Iye Idolorusan ruled the kingdom for a time in the nineteenth century, but seems to have never been formally designated a monarch.[9]"
    },
    {
        id:7,
        image: "https://atuwatseiii.com/assets/img/crests/iwere_kings/akengbuwa.jpg",
        name: "Eyeolusan João Akengbuwa",
        span: "Unknown - 14 June 1848",
        reign: 'Reign' ,
        start: "<b>Start:</b> 1795 ",
        end: "<b>End:<b> 14 June 1848",
        family: "Itsekiri",
        biography: "16th Olu. He succeeded his father. He was the last ruling king of the Itsekiri and the last Catholic Olu."
    },
    {
        id:8,
        image: "https://atuwatseiii.com/assets/img/crests/iwere_kings/erejuwa.jpg",
        name: "Sebastião Manuel Octobia Erejuwa I",
        span: "Unknown - 1795",
        reign: 'Reign' ,
        start: "<b>Start:</b> 1760",
        end: "<b>End:<b> 1795",
        family: "Itsekiri",
        biography: "15th Olu. He succeeded his father."
    },
    {
        id:9,
        image: "https://atuwatseiii.com/assets/img/crests/iwere_kings/atogbuwa.jpg",
        name: "Manuel Octobia Atogbuwa",
        span: "Unknown - 1760",
        reign: 'Reign' ,
        start: "<b>Start:</b> 1734",
        end: "<b>End:<b> 1760",
        family: "Itsekiri",
        biography: "14th Olu. He succeeded his father."
    },
    {
        id:10,
        image: "https://atuwatseiii.com/assets/img/crests/iwere_kings/akenjioye.jpg",
        name: "Agostinho Sabastião Octobia Akengboye",
        span: "Unknown - 1732",
        reign: 'Reign' ,
        start: "<b>Start:</b> 1730",
        end: "<b>End:<b> 1734",
        family: "Itsekiri",
        biography: "13th Olu. He succeeded his father."
    },
    {
        id:11,
        image: "https://atuwatseiii.com/assets/img/crests/iwere_kings/omagboye.jpg",
        name: "Miguel Omagboye",
        span: "Unknown - 1730",
        reign: 'Reign' ,
        start: "<b>Start:</b> 1709",
        end: "<b>End:<b> 1730",
        family: "Itsekiri",
        biography: "12th Olu. He succeeded his father."
    },
    {
        id:12,
        image: "https://atuwatseiii.com/assets/img/crests/iwere_kings/akenjioye_sebastien.jpg",
        name: "Sebastião II Akenjoye",
        span: "Unknown - 1709",
        reign: 'Reign' ,
        start: "<b>Start:</b>  1701",
        end: "<b>End:<b> 1701",
        family: "Itsekiri",
        biography: "11th Olu. He succeeded his father. As a prince he was known as Dom Ludivico Domingo."
    },
    {
        id:13,
        image: "https://atuwatseiii.com/assets/img/crests/iwere_kings/abejeoye.jpg",
        name: "Luigi Abejeoye",
        span: "Unknown - 1701",
        reign: 'Reign' ,
        start: "<b>Start:</b> 1674",
        end: "<b>End:<b> 1701",
        family: "Luso Itsekiri",
        biography: "10th Olu. He succeeded his father."
    },
    {
        id:14,
        image: "https://atuwatseiii.com/assets/img/crests/iwere_kings/omoluyiri.jpg",
        name: "Matias Ludovico Omoluyiri",
        span: "Unknown - 1674",
        reign: 'Reign' ,
        start: "<b>Start:</b> 1654",
        end: "<b>End:<b> 1674",
        family: "Luso Itsekiri",
        biography: "9th Olu. He succeeded his brother."
    },
    {
        id:15,
        image: "https://atuwatseiii.com/assets/img/crests/iwere_kings/oyenakpagha.jpg",
        name: "Antonio Domingos Oyenakpagha Obanighenren",
        span: "Unknown - 1653",
        reign: 'Reign' ,
        start: "<b>Start:</b> 1643",
        end: "<b>End:<b> 1654",
        family: "Luso Itsekiri",
        biography: "8th Olu. He succeeded his father. On ascension to the throne he was named Obanighenren which translates to 'Prince/King with the golden skin'. He wrote a letter to Pope Clement X in 1652 which was delivered to the Pope successfully. He was educated at home and at an institute in Angola. Like his father, he married a Portuguese lady."
    },
    {
        id:16,
        image: "https://atuwatseiii.com/assets/img/crests/iwere_kings/atuwatse.jpg",
        name: "Domingos Atuwatse I",
        span: "Unknown - 1643",
        reign: 'Reign' ,
        start: "1<b>Start:</b> 625",
        end: " <b>End:<b> 1643",
        family: "",
        biography: "7th Olu. He succeeded his father. He was initially home schooled by his father and the Bishop in Ode-Itsekiri, which resulted in him being able to read and write in Portuguese. He was later educated in Coimbra, Portugal from 1600 to 1611. He returned as a graduate, making him the first graduate in Sub Saharan Africa. Olu Dom Domingos was the first to marry a noble Portuguese lady, that came with him in 1611."
    },
    {
        id:17,
        image: "https://atuwatseiii.com/assets/img/crests/iwere_kings/atonrongboye.jpg",
        name: "Sebastião Atorongboye",
        span: "Unknown - 1625",
        reign: 'Reign' ,
        start: "<b>Start:</b> 1597",
        end: "<b>End:<b> 1625",
        family: "Itsekiri",
        biography: "6th Olu. He succeeded his father. He was born Prince Eyomasan. He was the first Catholic Olu, in fact every king after him until 1848 was so. He had a strong tie with King Philip II of Spain, who ruled Portugal at the time. This relation led to him sending his son to study in Coimbra, Portugal from 1600 to 1611. He and all future kings were awarded the title of Dom (D.)."
    },
    {
        id:18,
        image: "https://atuwatseiii.com/assets/img/crests/iwere_kings/esigie.jpg",
        name: "Esigie",
        span: "Unknown - 1597",
        reign: 'Reign' ,
        start: "<b>Start:</b> 1570",
        end: "<b>End:<b> 1597",
        family: "Itsekiri",
        biography: "5th Olu.He succeeded his father."
    },
    {
        id:19,
        image: "https://atuwatseiii.com/assets/img/crests/iwere_kings/ojoluwa.jpg",
        name: "Ojoluwa",
        span: "Unknown - 1570",
        reign: 'Reign' ,
        start: "<b>Start:</b> 1550",
        end: "<b>End:<b> 1570",
        family: "Itsekiri",
        biography: "4th Olu. He succeeded his father. During his reign, he commenced the process of integration of the Ekpen's/Ekpenede, descendants of Okere with the local population in the kingdom."
    },
    {
        id:20,
        image: "https://atuwatseiii.com/assets/img/crests/iwere_kings/irame.jpg",
        name: "Irame",
        span: "Unknown - 1550",
        reign: 'Reign' ,
        start: "<b>Start:</b> 1538",
        end: "<b>End:<b> 1550",
        family: "Itsekiri",
        biography: "3rd Olu. He succeeded his brother. It is stated that he banished the three gods (Ibirikimo, Otueke, and Ike) and their worshipers from Ode-Itsekiri-Olu (Big Warri) because of their incessant noise-making. The gods and their worshipers moved to Orugbo which is a community about 3 km from Ode-Itsekiri-Olu."
    },
    {
        id:21,
        image: "https://atuwatseiii.com/assets/img/crests/iwere_kings/ijijen.jpg",
        name: "Ijijen Ogbowuru",
        span: "Unknown - 1510",
        reign: 'Reign' ,
        start: "<b>Start:</b> 1510",
        end: "<b>End:<b> 1538",
        family: "Itsekiri",
        biography: "2nd Olu. He succeeded his father. He was the first King to reach Ode-Itsekiri (Big Warri) as his father settled down at Ijala community which became the burial place for all future Olu's."
    },
]

// council of chief data
export const rulingDetails = [
    {
        id: 1,
        image: "../assets/traditional_council.c46b6481ee3834488048.jpg",
        name: "Chief Johnson Amatserunleghe",
        title: " The Iyatsere of Warri",
        appellation: " Uji",
    },
    {
        id: 2,
        image: "../assets/traditional_council.c46b6481ee3834488048.jpg",
        name: "Chief Gabriel Awala",
        title: " The Uwangue of Warri",
        appellation: "Orieku",
    },
    {
        id: 3,
        image: "../assets/traditional_council.c46b6481ee3834488048.jpg",
        name: "Chief T.Y. Pessu",
        title: " The Ojomo of Warr",
        appellation: "Utioba",
    },
    {
        id: 4,
        image: "../assets/traditional_council.c46b6481ee3834488048.jpg",
        name: "Chief Sunday Rone",
        title: " The Obazuaye of Warri",
        appellation: "<b>Ogienoyibo",
    },
    {
        id: 5,
        image: "../assets/traditional_council.c46b6481ee3834488048.jpg",
        name: "Chief (Dr.) P.E.B. Uku",
        title: " The Ere Oluyon of Warri",
        appellation: "Ere-Egwa",
    },
    {
        id: 6,
        image: "../assets/traditional_council.c46b6481ee3834488048.jpg",
        name: "Chief G.T. Grant",
        title: " The Agura-Otiri of Warri",
        appellation: "Agbusibiro",
    },
    {
        id: 7,
        image: "../assets/traditional_council.c46b6481ee3834488048.jpg",
        name: "Chief (Mrs.) R. L. Ogbebor",
        title: " The Igba of Warri",
        appellation: "Irojowo",
    },
    {
        id: 8,
        image: "../assets/traditional_council.c46b6481ee3834488048.jpg",
        name: "Chief Kofi Kartey",
        title: "The Abolujiyan of Warri",
        appellation: "Ebirenegbo",
    },
    {
        id: 9,
        image: "../assets/traditional_council.c46b6481ee3834488048.jpg",
        name: "Chief Brown Mene",
        title: " The Ogwaolusan of Warri",
        appellation: "Esemuede",
    },
    {
        id: 10,
        image: "../assets/traditional_council.c46b6481ee3834488048.jpg",
        name: "Chief Elder Walter Odeli (JP)",
        title: " The Oritsegbogwa of Warri",
        appellation: "Oritsetsolatse",
    },
    {
        id: 11,
        image: "../assets/traditional_council.c46b6481ee3834488048.jpg",
        name: "Chief (Sir) E. T. Heymann (KSQ)",
        title: " The Eyeoluyon of Warri",
        appellation: "Adugeneyindolo",
    },
    {
        id: 12,
        image: "../assets/traditional_council.c46b6481ee3834488048.jpg",
        name: "Chief (Dr.) R. L. Oritsejafor",
        title: " The Ogwa of Warri",
        appellation: "Uwa-Eye",
    },
    {
        id: 13,
        image: "../assets/traditional_council.c46b6481ee3834488048.jpg",
        name: "Chief Felix Esisi",
        title: " The Olare-Aja of Okere",
        appellation: "Ogieboro",
    },
    {
        id: 14,
        image: "../assets/traditional_council.c46b6481ee3834488048.jpg",
        name: "Chief (Sir) P. D. Yalaju (KSQ)",
        title: " The Kenekuniraro of Warri",
        appellation: "Adolo",
    },
    {
        id: 15,
        image: "../assets/traditional_council.c46b6481ee3834488048.jpg",
        name: "Chief Francis Omatseye",
        title: " The Edigbe of Warri",
        appellation: "Ujatoli",
    },
    {
        id: 16,
        image: "../assets/traditional_council.c46b6481ee3834488048.jpg",
        name: "Chief Engr. Oma Eyewuoma",
        title: " The Aboludero of Warri",
        appellation: "Oyan",
    },
    {
        id: 17,
        image: "../assets/traditional_council.c46b6481ee3834488048.jpg",
        name: "Chief (Madam) Roli O. Oritsejafor",
        title: " The Iyeolumaete of Warri",
        appellation: "Ogbodu – Iyawa",
    },
    {
        id: 18,
        image: "../assets/traditional_council.c46b6481ee3834488048.jpg",
        name: "Chief Otimeyin Adams",
        title: " The Aguinode of Warri",
        appellation: "Ojowuro",
    },
    {
        id: 19,
        image: "../assets/traditional_council.c46b6481ee3834488048.jpg",
        name: "Chief Thomas Ereyitomi",
        title: " The Akatigbi –Ayeola of Warri",
        appellation: "Ojogbojo",
    },
    {
        id: 20,
        image: "../assets/traditional_council.c46b6481ee3834488048.jpg",
        name: "Chief Richmond O. McGray",
        title: " The Oritseboluwor of Warri",
        appellation: "Ogiaganusi",
    },
    {
        id: 21,
        image: "../assets/traditional_council.c46b6481ee3834488048.jpg",
        name: "Chief Billy Besigiwa",
        title: " The Osolo of Warri",
        appellation: "Ogboge - Nijebu",
    },
    {
        id: 22,
        image: "../assets/traditional_council.c46b6481ee3834488048.jpg",
        name: "Chief Eddy Eyitemi Olley",
        title: " The Agbarame (Ofone) of Warri",
        appellation: "Eni",
    },
    {
        id: 23,
        image: "../assets/traditional_council.c46b6481ee3834488048.jpg",
        name: "Chief Roland A. Omagbemi",
        title: " The Ewolufun of Warri",
        appellation: "Ogban",
    },
    {
        id: 24,
        image: "../assets/traditional_council.c46b6481ee3834488048.jpg",
        name: "Chief Engr. Anthony Onuwaje",
        title: " The Aboluwo of Warri",
        appellation: "Onogunjegbe",
    },
    {
        id: 25,
        image: "../assets/traditional_council.c46b6481ee3834488048.jpg",
        name: "Chief Fred Ogbe",
        title: " The Idorsu of Warri",
        appellation: "Eginoghoyo",
    },
    {
        id: 26,
        image: "../assets/traditional_council.c46b6481ee3834488048.jpg",
        name: "Chief Prest Udueyin",
        title: " The Akwinitsokan of Warri",
        appellation: "Adobodoji",
    },
    {
        id: 27,
        image: "../assets/traditional_council.c46b6481ee3834488048.jpg",
        name: "Chief (Mrs.) Mercy Olowu",
        title: " The UtukpaOritse Erun of Warri",
        appellation: "Eriegwa",
    },
    {
        id: 28,
        image: "../assets/traditional_council.c46b6481ee3834488048.jpg",
        name: "Chief Eyitemi Arthur Diden",
        title: " The IdeOfene of Warri",
        appellation: "Agboburukunjakan",
    },
    {
        id: 29,
        image: "../assets/traditional_council.c46b6481ee3834488048.jpg",
        name: "Chief Omolubi Newuwumi",
        title: " The Oma Tamudenyin of Warri",
        appellation: "Egindeghere Ugbo",
    },
    {
        id: 30,
        image: "../assets/traditional_council.c46b6481ee3834488048.jpg",
        name: "Chief Clement Akpeto Maleghemi",
        title: " The Udefi of Warri",
        appellation: "Obaloye",
    },
    {
        id: 31,
        image: "../assets/traditional_council.c46b6481ee3834488048.jpg",
        name: "Chief Dr. (Mrs.) Caroline Ajuyah",
        title: " The Olunuranran of Warri",
        appellation: "Iro’lobe",
    },
    {
        id: 32,
        image: "../assets/traditional_council.c46b6481ee3834488048.jpg",
        name: "Chief Dr. Joseph S. Otumara",
        title: " The Obarisuwa of Warri",
        appellation: "Osuolele",
    },
    {
        id: 32,
        image: "../assets/traditional_council.c46b6481ee3834488048.jpg",
        name: "Chief Solomon Arenyeka",
        title: " The Eson of Warri",
        appellation: "Otueje",
    },
    {
        id: 33,
        image: "../assets/traditional_council.c46b6481ee3834488048.jpg",
        name: "Chief Sam Amatotsero",
        title: " The Oluyemi of Warri",
        appellation: "Omotsonighele",
    },
    {
        id: 34,
        image: "../assets/traditional_council.c46b6481ee3834488048.jpg",
        name: "Chief Francis Maku",
        title: " The Ikenlorire of Warri",
        appellation: " Ijeguen",
    },
    {
        id: 35,
        image: "../assets/traditional_council.c46b6481ee3834488048.jpg",
        name: "Chief Luck Ereku",
        title: " The AtsetinOlu of Warri",
        appellation: " Ogiesamalele",
    },
    {
        id: 36,
        image: "../assets/traditional_council.c46b6481ee3834488048.jpg",
        name: "Chief Alex Omaghomi",
        title: " The Imaran of Warri",
        appellation: " Omayoye",
    },
    {
        id: 37,
        image: "../assets/traditional_council.c46b6481ee3834488048.jpg",
        name: "Chief (Mrs.) Winifred Agbejule",
        title: " The Oyeifo of Warri",
        appellation: " Otsowode",
    },
    {
        id: 38,
        image: "../assets/traditional_council.c46b6481ee3834488048.jpg",
        name: "Chief (Mrs.) Patricia Otuedon Arawore",
        title: " The AtsejuOlu of Warri",
        appellation: " Ogifie",
    },
    {
        id: 39,
        image: "../assets/traditional_council.c46b6481ee3834488048.jpg",
        name: "Chief Prof. Itse Sagay",
        title: " The Olufusi of Warri",
        appellation: " Ogodobiri",

    },
    {
        id: 40,
        image: "../assets/traditional_council.c46b6481ee3834488048.jpg",
        name: "Chief Tunde Okoturo",
        title: " The Ugo of Warri",
        appellation: " Ugoniwere",
    },
    {
        id: 41,
        image: "../assets/traditional_council.c46b6481ee3834488048.jpg",
        name: "Chief Leemon Ikpea",
        title: " The Odolagbon of Warri",
        appellation: " Edemayogho",
    },
    {
        id: 42,
        image: "../assets/traditional_council.c46b6481ee3834488048.jpg",
        name: "Chief Sen. Daisy Danjuma",
        title: " The AguraIwere of Warri",
        appellation: " Ewakpakpa",
    },
    {
        id: 43,
        image: "../assets/traditional_council.c46b6481ee3834488048.jpg",
        name: "Chief Fred Edegbele",
        title: " The Ikenuwa of Warri",
        appellation: " Orurunagbakiridi",
    },
    {
        id: 44,
        image: "../assets/traditional_council.c46b6481ee3834488048.jpg",
        name: "Chief Michael Odeli",
        title: " The Olorogun of Warri",
        appellation: " Okolokotuse",
    },
    {
        id: 45,
        image: "../assets/traditional_council.c46b6481ee3834488048.jpg",
        name: "Chief Akoma Demiyin",
        title: " The Omoku of Warri",
        appellation: " Egbewu",
    },
    {
        id: 46,
        image: "../assets/traditional_council.c46b6481ee3834488048.jpg",
        name: "Chief Barr. Edward Ekpoko",
        title: " The Tolureju of Warri",
        appellation: " Erebeni",
    },
    {
        id: 47,
        image: "../assets/traditional_council.c46b6481ee3834488048.jpg",
        name: "Chief Amanoritsewo Atiwa",
        title: " The Otsoron of Warri",
        appellation: " Edegberoko",
    },
    {
        id: 48,
        image: "../assets/traditional_council.c46b6481ee3834488048.jpg",
        name: "Chief (Barr.) Olivia Agbajoh",
        title: " The Oyewumi of Warri",
        appellation: " Egudeghe",
    },
    {
        id: 49,
        image: "../assets/traditional_council.c46b6481ee3834488048.jpg",
        name: "Chief (Barr.) Robinson Ariyo",
        title: " The Egogo Iwere of Warri",
        appellation: " Arayuwa",
    },
    {
        id: 50,
        image: "../assets/traditional_council.c46b6481ee3834488048.jpg",
        name: "Chief Tony Ede",
        title: " The Uwa Olu Etan of Warri",
        appellation: " Eribonosioba",
    },
    {
        id: 51,
        image: "../assets/traditional_council.c46b6481ee3834488048.jpg",
        name: "Chief Eugene Ikomi",
        title: " The Olulaye of Warri",
        appellation: " Oghoroju",
    },
    {
        id: 52,
        image: "../assets/traditional_council.c46b6481ee3834488048.jpg",
        name: "Chief Emmanuel Uduaghan",
        title: " The Alema of Warri",
        appellation: " Agbegherendiden",
    },
    {
        id: 53,
        image: "../assets/traditional_council.c46b6481ee3834488048.jpg",
        name: "Chief Emmanuel O. Ejutse",
        title: "  The Uranran Ogiame of Warri",
        appellation: " Ekoro-Usin",
    },
    {
        id: 54,
        image: "../assets/traditional_council.c46b6481ee3834488048.jpg",
        name: "Chief Dr. Mogba Eyeoyibo",
        title: " The Ogholuwarami of Warri",
        appellation: " Otsofu",
    },
    {
        id: 55,
        image: "../assets/traditional_council.c46b6481ee3834488048.jpg",
        name: "Chief Josephine Onemu",
        title: " The Ogwa Olu Ete of Warri",
        appellation: " Eperugo",
    },
]